import type { Metadata } from "next";
import "./globals.css";
import TeacherMenu from "@/components/calendar/teachers/teacher-menu";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div className="flex min-h-screen">
          <aside className="w-64 border-r bg-gray-50">
            {/* Teacher Management Menu */}
            <TeacherMenu />
          </aside>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
